### ISSUE TITLE
what is the difference between other one ( logseq-wide-eyed)

### ISSUE THREAD

**Issue by hodanli** [mlanza/logseq-style-carousel#1]
what is the difference between other one ( logseq-wide-eyed)

**Comment by mlanza** [comment]
The other one tries to keep track of everything which gets loaded to the page via DataScript queries.  It's cumbersome because doing this adds overhead.  And I can't possibly guess every block which will get loaded to or updated on a page.  It makes it a little more brittle.  I have to poll the page to.

Take Journals.  That page lazily loads content.  I have no idea how far down a person will scroll and how many days of entries they will load so I query 90 days out.  But if they scroll 91 days or further I'm not going to be hiding/manipulating any other blocks.  It's the reason I requested certain features ([event hooks to let me know when blocks are loaded/updated on a page](https://discuss.logseq.com/t/add-more-event-hooks-subscriptions-for-plugins/5508)) because then I could just tap into what the main app is already doing.

The other huge difference is Wide Eyed is matching regular expressions against content.  It can match anything at all (e.g. full text search) in the content, where as Style Carousel can only match against the kinds of metadata the core chooses to make visible in the DOM.  It is much more restrictive it what can be matched because CSS selectors can't do what a regular expression can.  So it is a compromise.  Yes, both do the same thing initially, by default, but both are configured in very different ways.  And neither was meant exclusively as means of toggling to-do visibility.  They just showcase what they can be made to do.  Both could be made to do dozens of other things.

Style Carousel is constantly matching the actual DOM and Wide Eyed is constantly presuming what's being loaded to the page and matching the actual content.  Style Carousel works better with trivial use cases like to-dos.  Fortunately, there is enough being added to the DOM to make this use case work fine.  That's because all the statuses (DONE, CANCELED, WAITING, etc.) are written to selectable attributes on elements.  This make Style Carousel light weight by comparison.  Until certain event hooks are added Wided Eyed is a cumbersome beast.

Both are configurable, but the average user is going to have more success with Style Carousel.  They're going to simply look at the DOM and design custom stylesheets that are conditionally toggled on/off.  Wide Eyed can match any content whatsoever, even if it's not exposed in the DOM.  Additionally, because Style Carousel is so light weight, it affords as many buttons as you like, whereas Wided Eyed presents a single button.

So to summarize, it depends on which capabilities you need: can you get away with just inspecting the DOM or do you want to inspect and match actual database content and metadata not presented in the DOM?

If I had my event hooks Wide Eyed could probably be made to do the same thing equally well and also be light weight.  But I do not have my event hooks.  So Wide Eyed is a kludge.  It works reasonably well given its constraints.  But as one user asked, "Why are some of my to-dos still showing?"  And that's because I have to presume what might get loaded on a page (in Wide Eyed) and I have no foolproof way of doing that.  

For example, I considered reading in the embedded queries and running them to get and match the content but at that point I felt like I was taking something which was already doing too much work and giving it even more work.  What's really needed to simplify are the event hooks.  If a page was simply announcing (via hooks) any block it rendered (e.g. the actual object with id, metadata, and content) then I wouldn't have to simply guess what might be loaded on a page.

If I might put it another way, and sorry to have drawn this out... consider how you might have designed a configurable plugin for conditionally styling content.  My intent was never to make it just about to-dos.  I wanted the user to be able to match on tags, phrases, schedules, deadlines, etc.  Wide Eyed can be made to do that.  Style Carousel cannot, unless all the metadata bubbles up to the DOM in a way conducive to selectors.  But that is an implementation specific dependency.  If the nature of the rendering changes, selectors will break.  Ideally, what you want are event hooks that tell you what's being added to (or updated on) the page and what area of the page (main content, side bar, etc.).  Simply announcing that with hooks would be powerful and allow a plugin like Wide Eyed to match on nearly every property.

**Comment by hodanli** [comment]
thanks for a very very detailed answer. it seems style carousel is better for me. in my experience wide eye could not perform well and was slow relative to carousel

**Comment by mlanza** [comment]
Agreed.  I went back to the drawing board.  If the added/updated hooks I requested are ever added Wide Eyed would become the superior option as it could do much, much more without the performance bottleneck.  Right now, both serve a purpose because Wide Eyed can still do more but, as you said, it is not snappy.

**Comment by mlanza** [comment]
@hodanli — Unfortunately, even the approach used by Style Carousel has problems when installed from the marketplace.  It fails to detect matches on the page, the feature which underlines the eye when completed/canceled to-dos are found on a page.  Everything else works fine.

Plus, if you install it locally (e.g. unpack the plugin) locally it works completely, all features.

**Comment by mlanza** [comment]
Per the latest release, Wide Eyed is now obsoleted by Style Carousel.  Wide Eyed works far too hard to track what is on the current page, unfortunately, because the Logseq plugin api doesn't help the situation.  

Style Carousel ignores the current page and, when queries are optionally used, queries across the entire database and builds style rules that can be applied to any page to achieve the desired effect.

Style Carousel's one deficit is the need to install it locally for the reasons described in the [README](https://github.com/mlanza/logseq-style-carousel#readme).
