### ISSUE TITLE
Hiding DONE does not work for block references

### ISSUE THREAD

**Issue by florianjehn** [mlanza/logseq-style-carousel#8]
Nice tool. Problem is that I often use block references for my to dos and it is not hiding those. Is there some way to also hide DONE block references?

**Comment by mlanza** [comment]
That's right.  Style Carousel has a single purpose: to dynamically apply styles based on what appears in the DOM.  Hiding DONE items is just a default demonstration of this higher purpose.

Unfortunately, block refs which are marked done don't share the same DOM attributes (CSS selectability) as normal blocks.  Normal todo blocks have a `data-self-refs="["done"]"` attribute.  This is what Carousel styles around for purposes of hiding DONE blocks.  These attributes exist in the DOM automatically, free of charge because it's just the way Logseq marks todos natively.  

But it doesn't add the same attributes on block refs, unfortunately, so what you want isn't free.  The Classy plugin I wrote could be used to locate block refs and dynamically add attributes/classes to the DOM, but this would take a bit of developer work and might require ongoing maintenance.  Plus because Classy polls and intermittently updates the DOM with the attributes Carousel requires this adds some overhead and is not free.

If this request expands to suit a wider audience/need I may take it on, but until then it's a use case I don't intend to maintain  Sorry.

If Logseq would allow Plugin authors to tap into the rendering pipeline what you want would become much lower hanging fruit and would not require the polling approach of Classy:
[Add plugin rendering pipeline - Feature Requests - Logseq](https://discuss.logseq.com/t/add-plugin-rendering-pipeline/5549)

**Comment by florianjehn** [comment]
Thanks for the clarification
